# Generated by Django 5.2 on 2025-05-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='项目编号')),
                ('description', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='项目预算')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('location_lat', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('location_lon', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('status', models.CharField(choices=[('planning', '规划中'), ('in_progress', '进行中'), ('completed', '已完成'), ('suspended', '已暂停'), ('cancelled', '已取消')], default='planning', max_length=20, verbose_name='项目状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-created_at'],
            },
        ),
    ]
